export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const SETUP_USER_BEGIN = " SETUP_USER_BEGIN";
export const SETUP_USER_SUCCESS = " SETUP_USER_SUCCESS";
export const SETUP_USER_ERROR = " SETUP_USER_ERROR";

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const LOGOUT_USER = "LOGOUT_USER";

export const GET_USER_BEGIN = "GET_USER_BEGIN";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";

export const SETUP_MEDICINE_BEGIN = " SETUP_MEDICINE_BEGIN";
export const SETUP_MEDICINE_SUCCESS = " SETUP_MEDICINE_SUCCESS";
export const SETUP_MEDICINE_ERROR = " SETUP_MEDICINE_ERROR";

export const GET_MEDICINE_BEGIN = "GET_MEDICINE_BEGIN";
export const GET_MEDICINE_SUCCESS = "GET_MEDICINE_SUCCESS";
